# Note: replicating nixpkgs pythonManyLinuxPackages
MANYLINUX_LIBS: set[str] = set(
    (
        "libgcc_s.so.1",
        "libstdc++.so.6",
        "libm.so.6",
        "libdl.so.2",
        "librt.so.1",
        "libc.so.6",
        "libnsl.so.1",
        "libutil.so.1",
        "libpthread.so.0",
        "libresolv.so.2",
        "libX11.so.6",
        "libXext.so.6",
        "libXrender.so.1",
        "libICE.so.6",
        "libSM.so.6",
        "libGL.so.1",
        "libgobject-2.0.so.0",
        "libgthread-2.0.so.0",
        "libglib-2.0.so.0",
        "libz.so.1",
        "libexpat.so.1",
        "libpanelw.so.5",
        "libncursesw.so.5",
        "libcrypt.so.1",
    )
)
